vpc_cidr_block          = "10.0.0.0/16"
vpc_tag                 = "es"
pub_subnet_cidr_block   = "10.0.0.0/28"
av_zone_pub             = "us-east-1a"
pub_subnet_tag          = "es_subnet"
pri_subnet_cidr_block   = ["10.0.1.0/28", "10.0.2.0/28", "10.0.3.0/28"]
av_zone_pri             = ["us-east-1a", "us-east-1b", "us-east-1c"]
pri_subnet_tag          = ["es_subnet-1", "es_subnet-2", "es_subnet-3"]
pub_ami                 = "ami-00874d747dde814fa"
pub_instance_type       = "t2.medium"
key_name                = "Virginia"
pub_instance_tag        = "es_bastion"
pri_ami                 = ["ami-00874d747dde814fa", "ami-00874d747dde814fa", "ami-00874d747dde814fa"]
pri_instance_type       = ["t2.medium", "t2.medium", "t2.medium"]
pri_instance_tag        = ["es-private1", "es-private2", "es-private3"]
sg_tag                  = ["es-master", "es-data1", "es-data2"]
igw_tag                 = "es-igw"
eip_tag                 = "es-eip"
nat_tag                 = "es-nat"
sg_cidr_block           = ["10.0.1.0/28", "10.0.2.0/28", "10.0.3.0/28"]
protocol                = "tcp"
rule_no                 = 200
action                  = "allow"
nacl_cidr_block         = "0.0.0.0/0"
from_port               = 0
to_port                 = 0
nacl_tag                = "ES-nacl"
rt_cidr_block           = "0.0.0.0/0"
public_route_table_tag  = "es-route_table_public"
private_route_table_tag = "es-route_table_private"
